### PR TITLE
human-metal: fix \m/ to represent 4 fingers instead of 5 \n/

### PR DESCRIPTION
**Pull request by Bigorneau**
Fix the emote of Human Metal.

If a single **\** is a finger, \m/ is a skaka-sign

Shaka sign

### CODE REVIEW

**Comment by madx** [comment]
lelno

**Comment by kud** [comment]
Euh?

**Comment by madx** [comment]
@kud laisse, c'est un autiste des smileys

**Comment by madx** [comment]
metal-hand

**Pull request closed without merging**
